FORMAT: 1A
HOST: http://172.18.218.192/

# gogogoSYSU

扫码点餐系统API详解

## SalersRe [/v1/salers]

关于商家注册的API介绍

### SalerRegister [POST]

+ Parameter
    + openID (required, string) - 用户ID
    + pw (required, string) - 用户密码
    + rtname (required, string) - 商家饭店名

+ Request (application/json)

    [
        {
            "openID":"lianqy",
            "pw":"lianqy",
            "rtname":"双鸭山饭店"
        }
    ]

+ Response 200 (application/json)

        [
            {
                "state":"OK"
            }
        ]

## SalersLo [/v1/salers/login]

关于商家登陆的API介绍

### SalerLogin [POST]

+ Parameter
    + openID (required, string) - 用户ID
    + pw (required, string) - 用户密码

+ Request (application/json)

        {
            "openID":"lianqy",
            "pw":"lianqy"
        }

+ Response 201 (application/json)

    + Body

            {
                "state":"OK"
            }
            
## RestaurantInfo [/v1/rt]

获取餐厅的信息

### RtInfo [GET]

+ Parameter
    + rtname (required, string)
    
+ Request (application/json)

    {
        "rtname":"双鸭山饭店"
    }
    
+ Response 201 (application/json)

    + Body
    
        {
            "rtname":"双鸭山饭店",
            "rtdes":"双鸭山出品，必是精品",
            "rtloc":"广州大学城",
            "rtphone":"12345678909",
            "rtlogo":"http://sysurt.org"
        }

## DishInfo [/v1/dish]

获取菜单中的菜品信息

### DishInfo [GET]

+ Parameter
    + rtname (required, string)
    
+ Request (application/json)

    {
        "rtname":"双鸭山饭店"
    }
    
+ Response 201 (application/json)

    + Body
        
        [
            {
                "dishname":"清蒸双鸭",
                "dishpict":"http://sysudoubleduck.org",
                "dishsale":"999",
                "dishprice":"￥99",
                "dishdis":"超级好吃！"
            }
        ]